<div class="main">
    <div class="container">
        <div class="main-info">
            <h1>Order Information</h1>
            <div class="form-left">
                <h1>Order Status</h1>
                <h2>Status : <?php echo $block->getOrderStatus(); ?></h2>
            </div>
            <div class="form-right">
                <h1>Grand Total</h1>
                <h2>Grand Total : <?php echo $block->getOrderGrandTotal(); ?></h2>
            </div>
            <div class="clear"> </div>
        </div>
    </div>
</div>


